### PR TITLE
Comments + bugs

### PR DESCRIPTION
**Pull request by jaiwiwjwjwisn**

### CODE REVIEW

**Comment by sfranzyshen** [comment]
Hi jaiwiwjwjwisn! 
Thank for you submission

I would like to know more about your pull request ... You have not provided any comments to your various commits ... you have 73 commits over 40 files with no info. It is difficult to tell if there are any code changes or just formatting changes. I can not tell from the github diff ... can you help me understand your pull request in a little more detail?

**Comment by jaiwiwjwjwisn** [comment]
I haven't tested on a physical device, but no changes with main code, just  formatting change and some code is shorted i believe

**Comment by sfranzyshen** [comment]
> I haven't tested on a physical device, but no changes with main code, just formatting change and some code is shorted i believe

the pull request, being all lumped together with no comments ... makes it very difficult to follow the changes ... Your interest to improve the current Otto API is welcomed ... and desired ... but maybe we can work together ... and collaborate to easy your ideas into the project ... please join the discord here https://discord.gg/qzFEdweW and then join the discussion for development here https://discord.com/channels/691410809586450483/1228242677963685918

thank you

**Review by sfranzyshen — CHANGES_REQUESTED** [review]
Your interest to improve the current Otto API is welcomed ... and desired ... but maybe we can work together ... and collaborate to easy your ideas into the project ... please refine your pull request to be commented and separated ... this pull request is difficult to follow and continually changing ... some of the changes may break older code ... and some changes have not been verified to work. 

please join the discord here https://discord.gg/qzFEdweW and then join the discussion for development here https://discord.com/channels/691410809586450483/1228242677963685918

**Comment by sfranzyshen** [comment]
Please resubmit with comments and separated into multiple pulls (create a temp branch) to help sort out what you are changing. Thank You

**Pull request closed without merging**
